### ISSUE TITLE
Read Access Violation in Window::RegisterCallbacks()

### ISSUE THREAD

**Issue by safi-huss** [jpvanoosten/LearningDirectX12#13]
Hi,

I am getting a read access violation when I reach this line;

`void Window::RegisterCallbacks(std::shared_ptr<Game> arg_pGame)
{
	m_pGame = arg_pGame; //Read Access violation here

	return;
}
`
I am new to this, but my hunch is that since we are passing it "shared_from_this", it may not be move assignable. I could be completely wrong too.

How would I fix it?

**Comment by jpvanoosten** [comment]
It looks like you've made some changes to the code. For example, `std::shared_ptr` is a template class but you are not specifying any template arguments in the code example.  It should be `std::shared_ptr<Game>` as can be seen here [DX12Lib/src/Window.cpp#L188](https://github.com/jpvanoosten/LearningDirectX12/blob/ecbacf76ee6e2dfb7a32d338b3d0f27d307d4a2d/DX12Lib/src/Window.cpp#L188).

Also, when using `shared_from_this`, your class must publicly inherit from `std::enable_shared_from_this<T>` (where `T` is the derived class) as can be seen here: [DX12Lib/inc/Game.h#L42](https://github.com/jpvanoosten/LearningDirectX12/blob/ecbacf76ee6e2dfb7a32d338b3d0f27d307d4a2d/DX12Lib/inc/Game.h#L42).

**Comment by safi-huss** [comment]
> It looks like you've made some changes to the code. For example, std::shared_ptr is a template class but you are not specifying any template arguments in the code example. It should be std::shared_ptr<Game> as can be seen here DX12Lib/src/Window.cpp#L188.

Sorry, I guess that was my mistake when trying to copy-paste the code and trying to get the code snippet to work. My code does have the template assigned.

`void Window::RegisterCallbacks(std::shared_ptr<Game> arg_pGame)
{
	m_pGame = arg_pGame;

	return;
}
`

Same goes for the class declarations as follows:

`class CGame : public std::enable_shared_from_this<CGame>
{
`

I tried changing the weak_ptr<Game> m_pGame to shared_ptr<Game> m_pGame, and commenting out the locks. but still, I get a similar error for Read Access violation.

Some of the ComPtr Objects are uninitialized at this point. Is that to be expected or have I bungled the code?

**Comment by safi-huss** [comment]
I believe I made a grave error in the code. Apparently, my window initialization was incorrect and I was using invalid handles to the Window to initialize the rest of the code.

Thank you so much for bearing my ineptitude. And a million thanks for writing these tutorials!
