### ISSUE TITLE
The GenerateProjectFiles.bat crash with VS2022

### ISSUE THREAD

**Issue by mtlau1968** [jpvanoosten/LearningDirectX12#16]
I got the following error message and not sure how to resolve it:
Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error:
  Running

   'C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe' '-C' 'C:/Users/mt_la/source/repos/LearningDirectX12/out/build/x64-Debug' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:3588: bad $-escape (literal $ must be written as $$)		C:\Users\mt_la\source\repos\LearningDirectX12\   ninja		

I added the following but still not working:
IF %VS_VERSION% == 17 (
    SET CMAKE_GENERATOR="Visual Studio 17 2022"
    SET CMAKE_BINARY_DIR=build_vs2022
) ELSE IF %VS_VERSION% == 16 (
    SET CMAKE_GENERATOR="Visua ...

**Comment by jpvanoosten** [comment]
Are you trying to open it in Visual Studio as a CMake folder?

**Comment by jpvanoosten** [comment]
What version of CMake are you using?

**Comment by jpvanoosten** [comment]
I removed cmake from the project. You must have cmake installed (see 7ffa42554178470b5715adbca70fb6eaa5648536)
