### ISSUE TITLE
Crash after minimizing the window

### ISSUE THREAD

**Issue by HannesVernooij** [jpvanoosten/LearningDirectX12#2]
When minimizing the window, the width and height are set to zero and then it tries to resize the RTV to zero which causes an issue on resizing the textures. Making sure that the width and height will not get below 1 in the resize event args will resolve this problem.

**Comment by jpvanoosten** [comment]
Hannes,

I believe this was fixed in c8578f262e8fcedff50e2fc35c55728e9c3897a0. Check lines 74-75 of that commit: [Texture.cpp](https://github.com/jpvanoosten/LearningDirectX12/commit/c8578f262e8fcedff50e2fc35c55728e9c3897a0#diff-45fa28970fbbfc9fa578506d3da216f7R74)
