### ISSUE TITLE
Minimal example to reproduce "D3D12_RESOURCE_STATES has bits that mismatch support required from D3D12_RESOURCE_FLAGS" Error

### ISSUE THREAD

**Issue by FireFlyForLife** [jpvanoosten/LearningDirectX12#3]
On Monday we were tracking a bug where loading the textures for a mesh would randomly cause the  DirectX error: `D3D12_RESOURCE_STATES has bits that mismatch support required from D3D12_RESOURCE_FLAGS`. 

I found a minimal way to reproduce this error. Firstly, write a simple loop (I put this in `Tutorial3::LoadContent()` ):
```cpp
auto commandQueue = Application::Get().GetCommandQueue(D3D12_COMMAND_LIST_TYPE_COPY);
Texture dummyTextures[20];
for (int i = 0; i < 20; ++i)
{
	auto commandList = commandQueue->GetCommandList();
	commandList->LoadTextureFromFile(dummyTextures[i], L"Assets/Textures/Directx9.png");
	auto fenceVal = commandQueue->ExecuteCommandList(commandList);
	commandQueue->WaitForFenceValue(fenceVal);
}
```

THEN you need to disable the cache check in `CommandList::LoadTextureFromFile()` so you are actually emulating loading a lot of different textures after each other. Otherwise the command doesn't do anything on the gpu.
```cpp
    ...
    auto iter = ms_TextureCache.find( fileName );
    if ( false /*iter != ms_TextureCache.end()*/ )
    {
        texture.SetTextureUsage(textureUsage);
        texture.SetD3D12Resource(iter->second);
        texture.CreateViews();
        texture.SetName(fileName);
    }
    else
    {
        TexMetadata metadata;
        ....
```

Then after usually ~5 iterations you will get the same error we know and love:
```
D3D12 ERROR: ID3D12CommandList::ResourceBarrier: D3D12_RESOURCE_STATES has bits that mismatch support required from D3D12_RESOURCE_FLAGS. [ RESOURCE_MANIPULATION ERROR #524: RESOURCE_BARRIER_MISMATCHING_MISC_FLAGS]
D3D12: **BREAK** enabled for the previous message, which was: [ ERROR RESOURCE_MANIPULATION #524: RESOURCE_BARRIER_MISMATCHING_MISC_FLAGS ]
Exception thrown at 0x00007FFF3DDAA388 (KernelBase.dll) in EngineLyra.exe: 0x0000087A (parameters: 0x0000000000000001, 0x000000B3B31F5470, 0x000000B3B31F7370).
Unhandled exception at 0x00007FFF3DDAA388 (KernelBase.dll) in EngineLyra.exe: 0x0000087A (parameters: 0x0000000000000001, 0x000000B3B31F5470, 0x000000B3B31F7370).
```

This makes me suspect that there is some unsafe deletions being made. You mentioned that the cleanup for staging resources and other temporary resources happens on a seperate thread. Perhaps something is not fully thread safe. I will do more debugging tomorrow to find out more.

**Comment by jpvanoosten** [comment]
This issues is fixed in d17b0ecf8760750ab5b9c42a5df32d944d03c2cc.
