### ISSUE TITLE
WARP

### ISSUE THREAD

**Issue by HSadeghein** [jpvanoosten/LearningDirectX12#4]
When I set` g_UseWarp = false`and build and run the program it will crash if I push "alt + enter" many times to go in the borderless state and back but it works perfectly when I set `g_UseWarp = true`
do you know exactly why?

**Comment by jpvanoosten** [comment]
I think I know why it was happening. The swap chain was being resized while one of the swap chain buffers were still being referenced on the command queue.

It's fixed in 7cf0abd4f41ec7064287c24930608d1bf303c875
