### ISSUE TITLE
CommandList add wrapper functions for setting inline SRV's and UAV's

### ISSUE THREAD

**Issue by FireFlyForLife** [jpvanoosten/LearningDirectX12#7]
Currently only the functions exist for binding them through a descriptor heap.

**Comment by jpvanoosten** [comment]
How could I have not addressed this yet?

**Comment by jpvanoosten** [comment]
@FireFlyForLife I've (finally) added the functions for binding:

- Inline SRV, UAV, and CBV's
- CBV in descriptor heaps

See 481e3fa2b37fa66cbafbd67519bbc4ad4f2d78a7
