### ISSUE TITLE
Iterator of m_AvailableHeaps after erase issue

### ISSUE THREAD

**Issue by ChemiaAion** [jpvanoosten/LearningDirectX12#8]
https://github.com/jpvanoosten/LearningDirectX12/blob/48223e1f652a4434f2d8c5c17908b524b865f053/DX12Lib/src/DescriptorAllocator.cpp#L39

We should redesign the for(...) loop to avoid a crash when `m_AvailableHeaps.erase(iter)` returns `iter.end()` and **then** is pre-incremented in the current version of for(...) loop.

Let's just move `++iter;` to the end of the current scope and add `continue();` after the mentioned line.

**Comment by jpvanoosten** [comment]
We can't use continue since the line after checks if a valid allocation was found.

Fixed in f579d5b.
