### ISSUE TITLE
Missing flushBarriers argument on AliasingBarrier and UAVBarrier

### ISSUE THREAD

**Issue by ChemiaAion** [jpvanoosten/LearningDirectX12#9]
Missing `flushBarriers` argument on:

https://github.com/jpvanoosten/LearningDirectX12/blob/dc7c1d9b11be863408890dce9d7d23aecea4f6c1/DX12Lib/src/CommandList.cpp#L83

https://github.com/jpvanoosten/LearningDirectX12/blob/dc7c1d9b11be863408890dce9d7d23aecea4f6c1/DX12Lib/src/CommandList.cpp#L100

**Comment by jpvanoosten** [comment]
Fixed in 5af740.
